apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solr
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
  #type: pd-ssd
  #replication-type: regional-pd
  #volumeBindingMode: WaitForFirstConsumer

